POST http://localhost:8080/applicant_technology/many
Content-Type: application/json


  {
  "applicant": {
    "applicantId": 402
  },
    "technology": {
        "technologyId": 359
    },
    "note": "Finish 42 core projects",
    "level": "Expert"
  }
