### Seznam technologii
GET http://localhost:8080/fetchAllTechnology

### Pridani technologie
POST http://localhost:8080/saveTechnologies
Content-Type: application/json

[
  {
    "technologyName": "Jira"
  },
  {
    "technologyName": "Java"
  },
  {
    "technologyName": "Spring"
  },
  {
    "technologyName": "GIT"
  },
  {
    "technologyName": "C-language"
  }
]

### Odebirani technologie
DELETE http://localhost:8080/removeTechnology/id/556

### Uprava technologie
PUT http://localhost:8080/updateTechnology/id/555
Content-Type: application/json

{
    "technologyName": "not-Jira"
}